### ISSUE TITLE
Notice: Undefined variable: recentlogin 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/xoopsmembers#32]
Notice: Undefined variable: recentlogin in file /modules/xoopsmembers/blocks/memberslastlogin_block.php line 26

**Comment by mambax7** [comment]
If it works for you, please close it

**Comment by liomj** [comment]
Now after the fix no member is listed as login recently

**Comment by mambax7** [comment]
OK, I'll have to create few users on my installation in order to test it :)

**Comment by liomj** [comment]
you should be listed as well as login recently

**Comment by mambax7** [comment]
I hope, it works now

**Comment by liomj** [comment]
> I hope, it works now

yes it is working now..i also made a pull request to fix Notice: Undefined variable: block for guest
