### ISSUE TITLE
working on new version of xoopsmembers 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/xoopsmembers#5]
Hi, im working on new version of xoopsmembers..here some of updates i made so far

	->Changed : Change index.php to Member List 
	->Added   : Duplicate index.php to searchmembers.php 
	->Changed : Change html template to tpl template
       ->Changed : Change image location to assets 
	->Changed : Update and rename language definition 

still work in progress

https://github.com/liomj/xoopsmembers

**Comment by mambax7** [comment]
It seems like it is now taking over the Website, i.e. the other blocks, incl. Menu, are disappearing:
![image](https://user-images.githubusercontent.com/613686/79065913-d4bcf480-7c81-11ea-9e15-b895756562eb.png)

If there is no menu, then I can't select the "Search" submenu

**Comment by mambax7** [comment]
I'm sorry, somehow the Menu was set to be only on the Top page. 
After I've changed that, it's all good now!

**Comment by liomj** [comment]
no problem Mamba. 
i notice the members perpage, sort and order by in index page now not working properly after the update

**Comment by liomj** [comment]
i also receive this error when installing the module

Error : Error: Class 'XoopsModules\Xoopsmembers\Helper' not found

after refresh the error is gone


XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28

**Comment by mambax7** [comment]
>Error : Error: Class 'XoopsModules\Xoopsmembers\Helper' not found


That should fix that: https://github.com/mambax7/xoopsmembers/commit/4f2b44723d918129545443fa6ed1f6e8fcdb08ef

**Comment by liomj** [comment]
Hi Mamba
I made a pull request Adding Online Status, Biography/Extra Info, Signature, Rank, Groups

please review it..Thank you

**Comment by mambax7** [comment]
Awesome!!! Thank you!

**Comment by liomj** [comment]
Hi Mamba, I made another pull request for XOOPS Members
